### ISSUE TITLE
no compile

### ISSUE THREAD

**Issue by dvastazion** [ashh87/clevo-wmi#3]
make -C /lib/modules/4.0.5-gentoo/build M=/home/dvastazion/dev/clevo-wmi/src modules
make[1]: se entra en el directorio '/usr/src/linux-4.0.5-gentoo'
  CC [M]  /home/dvastazion/dev/clevo-wmi/src/clevo-wmi.o
/home/dvastazion/dev/clevo-wmi/src/clevo-wmi.c:55:8: error: expected ‘;’, identifier or ‘(’ before ‘struct’
 static struct workqueue_struct *led_workqueue;
        ^
scripts/Makefile.build:264: fallo en las instrucciones para el objetivo '/home/dvastazion/dev/clevo-wmi/src/clevo-wmi.o'
make[2]: *** [/home/dvastazion/dev/clevo-wmi/src/clevo-wmi.o] Error 1
Makefile:1390: fallo en las instrucciones para el objetivo '_module_/home/dvastazion/dev/clevo-wmi/src'
make[1]: *** [_module_/home/dvastazion/dev/clevo-wmi/src] Error 2
make[1]: se sale del directorio '/usr/src/linux-4.0.5-gentoo'
Makefile:9: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

**Comment by ashh87** [comment]
please see #2
